config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'quizzes#index2'
  resources :quizzes, except: :show
  resources :users, only: :show
  resources :quizzes do
    resources :correctnesses, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/correctness.rb
class Correctness < ApplicationRecord
  belongs_to :quiz
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  validates :text, presence: true, length: { maximum: 60 }
  validates :answer, presence: true, format: { with: /\A[ぁ-ん０-９ー－]+\z/ }

  belongs_to :user
  has_many :correctnesses
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :quizzes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    end
end

app/controllers/correctnesses_controller.rb
class CorrectnessesController < ApplicationController
  def create
    Correctness.create(correctness_params)
  end
end

private
def correctness_params
  quiz = Quiz.find(params[:quiz_id])
  if quiz.answer == params[:text]
    params.permit(:quiz_id).merge(answer_flg: true)
  else
    params.permit(:quiz_id).merge(answer_flg: false)
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :ensure_correct_user, only: [:destroy, :edit, :update]

  def index
    quizzes = Quiz.all
    @quiz = quizzes.sample
    gon.answer = @quiz.answer
    correctnesses = @quiz.correctnesses
    @rate = rate(correctnesses)
  end

  def new
    @quiz = Quiz.new
  end

  def create
    @quiz = Quiz.new(quiz_params)
    if @quiz.save
      redirect_to root_path
      flash[:notice] = '投稿が完了しました'
    else
      flash.now[:alert] = '投稿に失敗しました'
      render :new
    end
  end

  def edit
    correctnesses = @quiz.correctnesses
    @rate = rate(correctnesses)
  end

  def update
    if @quiz.update(quiz_params)
      redirect_to root_path
      flash[:notice] = '編集が完了しました'
    else
      flash.now[:alert] = '編集に失敗しました'
      render :edit
    end
  end

  def destroy
    @quiz.destroy
    redirect_to root_path
    flash[:notice] = '削除が完了しました'
  end

private
  def quiz_params
    params.require(:quiz).permit(:text, :answer).merge(user_id: current_user.id)
  end

  def ensure_correct_user
    @quiz = Quiz.find(params[:id])
    if @quiz.user_id != current_user.id
       flash[:notice] = '権限がありません'
       redirect_to root_path
    end
  end

  def rate(correctnesses)
    if correctnesses.length == 0
      return 0
    else
      quantity = correctnesses.length
      correct_count = 0
      correctnesses.each do |correctness|
        correct_count += 1 if correctness.answer_flg == true
      end
      return correct_count * 100 / quantity
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    if user.id != current_user.id
      flash[:notice] = '権限がありません'
      redirect_to root_path
    end
    @quizzes = user.quizzes
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/correctnesses_helper.rb
module CorrectnessesHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title QuizPracticeApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = include_gon
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .notification
      - flash.each do |key, value|
        = content_tag :div, value, class: key
    .header
      .header__title
        %h1 早押し練習アプリ
      .header__right
        -if user_signed_in?
          .header__right__user
            =link_to current_user.nickname, edit_user_registration_path, class: 'header__right__user__link'
          .header__right__log
            =link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'header__right__log__link'
        -else
          .header__right__user
            =link_to '新規登録', new_user_registration_path, class: 'header__right__user__link'
          .header__right__log
            =link_to 'ログイン', new_user_session_path, class: 'header__right__log__link'
    .category
      .category__box
        =link_to '問題を解く', root_path, class: 'category__box__solving'
      .category__box
        -if user_signed_in?
          =link_to '問題を作成する', new_quiz_path, class: 'category__box__create'
        -else
          =link_to '問題閲覧・編集', new_user_session_path, class: 'category__box__edit'
      .category__box
        -if user_signed_in?
          =link_to '問題閲覧・編集', user_path(current_user.id), class: 'category__box__edit'
        -else
          =link_to '問題閲覧・編集', new_user_session_path, class: 'category__box__edit'
          
    = yield

app/views/quizzes/_quiz.html.haml
.content
  %p 問題：
  .content__text=quiz.text
  .content__right
    =icon 'fa', 'angle-down', class: 'content__right__icon'
    %ul.content__right__box
      %li=link_to '編集', edit_quiz_path(quiz), class: 'content__right__box__text'
      %li=link_to '削除', quiz_path(quiz), method: :delete, class: 'content__right__box__text'

app/views/quizzes/edit.html.haml
.new-contents
  %p.new-contents__title 問題編集フォーム
  .new-contents__box
    =form_with model: @quiz, local: true, class: 'new-contents__box__form' do |f|
      .new-contents__box__form__question="問題(正答率：#{@rate}%)"
      =f.text_area :text, placeholder: '６０字以内で記述してください', value: @quiz.text,class: 'new-contents__box__form__text'
      .new-contents__box__form__answer 答え(解答は全角のひらがな・数字・伸ばし棒(ー)での入力のみ対応しています)
      =f.text_field :answer, value: @quiz.answer,class: 'new-contents__box__form__answer-text'
      %br/
      =f.submit '投稿', class: 'new-contents__box__form__btn'

app/views/quizzes/index.html.haml
.main
  .main__question
    %p="問題(正答率：#{@rate}%)"
    .main__question__text
      =@quiz.text
  .main__btn
    =image_tag 'buzzer.png'
    %span.main__btn__message 
      ←分かったら
      %br
      &nbsp;&nbsp;&nbsp;押してね
  =form_with model: @correctness, url: quiz_correctnesses_path(@quiz),local: true, class: 'main__form' do |f|
    =f.text_field :text, placeholder: '全角のひらがな、数字、記号入力してください', class: 'main__form__text'
    =f.submit '解答する', class: 'main__form__btn'

app/views/quizzes/index2.html.haml
.cover
  .cover__illust
    =image_tag 'quiz_man_batsu.png', class: 'cover__illust__image'
    =image_tag 'quiz_woman_maru.png', class: 'cover__illust__image'
  .cover__start
    =link_to 'スタート', quizzes_path, class: 'cover__start__text'

app/views/quizzes/new.html.haml
.new-contents
  %p.new-contents__title 問題投稿フォーム
  .new-contents__box
    =form_with model: @quiz, local: true, class: 'new-contents__box__form' do |f|
      .new-contents__box__form__question 問題
      =f.text_area :text, placeholder: '６０字以内で記述してください', value: '',class: 'new-contents__box__form__text'
      .new-contents__box__form__answer 答え(解答は全角のひらがな・数字・伸ばし棒(ー)での入力のみ対応しています)
      =f.text_field :answer, class: 'new-contents__box__form__answer-text'
      %br/
      =f.submit '投稿', class: 'new-contents__box__form__btn'

app/views/users/shared/_error_messages.html.haml
- if resource.errors.any?
  #error_explanation
    %h2
      = I18n.t("errors.messages.not_saved",                 |
        count: resource.errors.count,                       |
        resource: resource.class.model_name.human.downcase) |
    %ul
      - resource.errors.full_messages.each do |message|
        %li= message

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "ログイン", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "新規登録", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "パスワードをお忘れですか?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/

app/views/users/show.html.haml
.contents
  %p.contents__title 作成問題一覧ページ
  =render @quizzes